spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        - id: file
          uri: lb://file-service
          predicates:
            - Path=/api/file/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
