name: h-nas
configs:
  mysql-config:
    file: ./mysql.cfg
services:
  redis:
    container_name: dragonfly-1
    image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
  nacos:
    container_name: nacos-1
    image: nacos/nacos-server:v3.0.0
    environment:
      MODE: standalone
      NACOS_AUTH_TOKEN: # nacos jwt token
      NACOS_AUTH_IDENTITY_KEY: nacos_key
      NACOS_AUTH_IDENTITY_VALUE: nacos
    ports:
      - "12888:8080"
  mysql:
    container_name: mysql-1
    image: mysql:9.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: h_nas
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    configs:
      - source: mysql-config
        target: /etc/mysql/conf.d/my.cnf
        mode: 0644
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
  user:
    image: h-nas/user-service:1.0.0
    environment:
      SPRING_DATA_REDIS_HOST: dragonfly-1
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-1:3306/h_nas
      SPRING_CLOUD_NACOS_SERVER_ADDR: nacos-1:8848
    ports:
      - "12001:12001"
    depends_on:
      mysql:
        condition: service_healthy
  file:
    image: h-nas/file-service:1.0.0
    environment:
      NVIDIA_DRIVER_CAPABILITIES: all
      SPRING_DATA_REDIS_HOST: dragonfly-1
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-1:3306/h_nas
      SPRING_CLOUD_NACOS_SERVER_ADDR: nacos-1:8848
    ports:
      - "12002:12002"
    runtime: nvidia
    volumes:
      - /usr/h-nas/data
      - /usr/h-nas/cache
    depends_on:
      mysql:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
  ai:
    image: h-nas/ai-service:1.0.0
    environment:
      SPRING_DATA_REDIS_HOST: dragonfly-1
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-1:3306/h_nas
      SPRING_CLOUD_NACOS_SERVER_ADDR: nacos-1:8848
      SPRING_AI_OLLAMA_BASE_URL: http://host.docker.internal:11434
      QWEATHER_HOST: # **.qweatherapi.com
      QWEATHER_JWT_PRIVATEKEY: # qweather jwt private key
      QWEATHER_JWT_KEYID: # qweather project key id
      QWEATHER_JWT_PROJECTID: # qweather project id
    ports:
      - "12999:12999"
    depends_on:
      mysql:
        condition: service_healthy
