spring:
  application:
    name: ai-service
  ai:
    ollama:
      chat:
        model: qwen3
        options:
          temperature: 0.65
          num-ctx: 4096
server:
  port: 12999
  jetty:
    connection-idle-timeout: 10s

