[package]
name = "l10n"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.39", features = ["derive"] }
json = "0.12.4"
regex = { version = "1.11.1", features = [] }
